---
# tasks file for ansible-role-debug

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Install epdb
  pip:
    name: epdb

- shell: "ansible --version"
  register: register_ansible
  changed_when: false

- shell: "ansible -m setup localhost > {{ debug_dump_file }}"
  # XXX `creates` is not used here because the dump file should always refelect
  # the most recent state. if `creates` is used, users might see stale information.
  changed_when: false
  when: "{{ debug_dump and register_ansible.rc == 0 }}"
